import express from "express";
import cors from "cors";
import { fileURLToPath } from "url";
import path from "path";
import morgan from "morgan";
import authRouter from "./Routes/auth.js";
import cartRouter from "./Routes/cart.js";
import categoryRouter from "./Routes/category.js";
import commentRouter from "./Routes/comment.js";
import discountRouter from "./Routes/discount.js";
import orderHistoryRouter from "./Routes/orderHistory.js";
import paymentRouter from "./Routes/payment.js";
import productRouter from "./Routes/product.js";
import reportRouter from "./Routes/report.js";
import sliderRouter from "./Routes/slider.js";
import userRouter from "./Routes/user.js";
import variantRouter from "./Routes/variant.js";
import HandleError from "./Utils/handleError.js";
import catchError from "./Utils/catchError.js";
const __filename = fileURLToPath(import.meta.url);
export const __dirname = path.dirname(__filename);
const app = express();
app.use(express.json());
app.use(express.static("Public"));
app.use(cors());
app.use(morgan("dev"));

app.use("/api/v1/auth", authRouter);
app.use("/api/v1/cart", cartRouter);
app.use("/api/v1/category", categoryRouter);
app.use("/api/v1/comment", commentRouter);
app.use("/api/v1/discount", discountRouter);
app.use("/api/v1/order-history", orderHistoryRouter);
app.use("/api/v1/payment", paymentRouter);
app.use("/api/v1/product", productRouter);
app.use("/api/v1/rep[ort", reportRouter);
app.use("/api/v1/slider", sliderRouter);
app.use("/api/v1/user", userRouter);
app.use("/api/v1/variant", variantRouter);
app.use("*", (req, res, next) => {
  return next(new HandleError("route not found", 404));
});
app.use(catchError);
export default app;
